Mini Projeto , Roosevelt Freire , T8

Link do guithub : https://github.com/Roomoceci/Miniprojeto_Rooseveltfreire_t8.git

Sprint 1

Etapa 1  Inportaçao da Base

Carregando  a Base (Base Varejo.csv), que  foi disponibilizado para  a analise de dados

In [4]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

nome_arquivo = next(iter(uploaded))

# Lendo o arquivo CSV definindo o caractere de ponto e vírgula como separador de colunas
df_original = pd.read_csv(nome_arquivo, sep=';')

Saving Base Varejo.csv to Base Varejo.csv

Diaguinostico  da base  a ser tratada conhecendo as linha e colunas

In [5]:
import pandas as pd

# Corrigido de pd.heade.csv para pd.read_csv com o separador correto
df = pd.read_csv("Base Varejo.csv", sep=';')

df_original = df.copy()

display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN


Estrutura da  Base

Investigando  os  dados, estruturas e tipos , a ser analizados .

In [6]:
# Quantidade de linhas  e colunas
print("Quantidade de linhas ", df.shape[0])
print("Quantitade de colunas ",df.shape[1])

Quantidade de linhas  830000
Quantitade de colunas  14

Total de  linha e colunas  da base

In [7]:
# Nomes das colunas
print(df.columns.tolist())

['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [8]:
# tipos  e quantidades de valores preenchidos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

Relatorio do Mini Projeto  da Base Varejo:

A base  possui 830000 registros e 14 colunas.Cada registro representa um valor presente.As principais colunas  sao : ('DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13')


Tratando os  valores ausentes

In [9]:
#Quantidade de valores ausentes existe por coluna
ausentes = df.isna().sum()
display(ausentes)

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [10]:
# Cauculando o percentual de ausentes
percentuais = (
    df.isna().mean() * 100
).round(2)



resumo_ausentes = pd.DataFrame({
    'Quantidade': ausentes,
    'Percentual': ausentes })
display(resumo_ausentes)
display(percentuais)

             Quantidade  Percentual
DATA                  0           0
CO_ID                 0           0
CL_ID                 0           0
CL_GENERO             0           0
CL_EC                 0           0
CL_FHL                0           0
CL_SEG                0           0
PR_ID                 0           0
PR_CAT                0           0
PR_NOME               0           0
Unnamed: 10      830000      830000
Unnamed: 11      830000      830000
Unnamed: 12      830000      830000
Unnamed: 13      830000      830000

DATA             0.0
CO_ID            0.0
CL_ID            0.0
CL_GENERO        0.0
CL_EC            0.0
CL_FHL           0.0
CL_SEG           0.0
PR_ID            0.0
PR_CAT           0.0
PR_NOME          0.0
Unnamed: 10    100.0
Unnamed: 11    100.0
Unnamed: 12    100.0
Unnamed: 13    100.0
dtype: float64

SPLINT 2


Verificando os valores duplicados nas  colunas

In [11]:
display(
    df.loc[
        df["Unnamed: 10"].isna(),
        ["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "CO_ID", "CL_ID", "CL_GENERO", "CL_EC", "CL_FHL", "CL_SEG", "PR_ID", "PR_CAT", "PR_NOME","DATA"]
    ]
)

,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,DATA
0,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,01/02/2019
1,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,01/02/2019
2,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,01/02/2019
3,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,01/02/2019
4,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,01/02/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,19/08/2022
829996,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,19/08/2022
829997,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,19/08/2022
829998,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,19/08/2022
829999,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,19/08/2022

Investigando  textos vazios e preenchidos com
espaços

In [12]:
colunas_analise = ["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "CO_ID", "CL_ID", "CL_GENERO", "CL_EC", "CL_FHL", "CL_SEG", "PR_ID", "PR_CAT", "PR_NOME","DATA"]

# Verifica se os registros são strings vazias após remover os espaços de cada coluna
registro_em_branco = (
    df[colunas_analise]
    .astype(str)
    .apply(lambda col: col.str.strip().eq(""))
    .any(axis=1)
)

print("registros preenchidos com espaços:", registro_em_branco.sum())

display(
    df.loc[
        registro_em_branco,
        colunas_analise
    ]
)

registros preenchidos com espaços: 0

Empty DataFrame
Columns: [Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, CO_ID, CL_ID, CL_GENERO, CL_EC, CL_FHL, CL_SEG, PR_ID, PR_CAT, PR_NOME, DATA]
Index: []

In [13]:
#combinaçao das duas situaçoes
colunas_analise = ["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "CO_ID", "CL_ID", "CL_GENERO", "CL_EC", "CL_FHL", "CL_SEG", "PR_ID", "PR_CAT", "PR_NOME","DATA"]

registro_em_branco = (
    df[colunas_analise]
    .astype(str)
    .apply(lambda col: col.str.strip().eq(""))
    .any(axis=1)

)
print(registro_em_branco.sum())
display(
    df.loc[
        registro_em_branco,
        colunas_analise
    ]
)

0

Empty DataFrame
Columns: [Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, CO_ID, CL_ID, CL_GENERO, CL_EC, CL_FHL, CL_SEG, PR_ID, PR_CAT, PR_NOME, DATA]
Index: []

Duplicatas - Investigaçao, de duplicidade .

In [14]:
print(
    "repetiçao completas alem da primeira ocorrencia ",
    df.duplicated().sum()
    ) # maraca as  repeticoes da primeira ocorrencia

print(
    "Linhas que tem grupos repetidos ",
    df.duplicated(keep=False).sum()

 ) # maraca as ocorrencias

print(
    "Identificaçao de registros destintos ",

    df[colunas_analise].nunique()

)

repetiçao completas alem da primeira ocorrencia  96553
Linhas que tem grupos repetidos  184330
Identificaçao de registros destintos  Unnamed: 10        0
Unnamed: 11        0
Unnamed: 12        0
Unnamed: 13        0
CO_ID          18471
CL_ID           1000
CL_GENERO          2
CL_EC              5
CL_FHL             5
CL_SEG             3
PR_ID            229
PR_CAT             7
PR_NOME          118
DATA             333
dtype: int64

In [15]:
# Vizualizaçao das linhas duplicadas
display(
    df.loc[
        df.duplicated(keep=False),
        colunas_analise
    ]
)

,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,DATA
3,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,01/02/2019
7,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,01/02/2019
14,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,01/02/2019
15,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,01/02/2019
19,NaN,NaN,NaN,NaN,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,01/02/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829989,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,19/08/2022
829992,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,19/08/2022
829995,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,19/08/2022
829996,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,19/08/2022
829997,NaN,NaN,NaN,NaN,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,19/08/2022

Incontigencia de texto  e  investigaçao de  categorias , canais e status

In [16]:
# Analisando a distribuição das categorias de produtos existentes
display(
    df["PR_CAT"].value_counts(dropna=False)
)

# Analisando a distribuição dos segmentos de clientes existentes
display(
    df["CL_SEG"].value_counts(dropna=False)
)

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

CL_SEG
B    530163
C    232101
A     67736
Name: count, dtype: int64

In [29]:
# 1. Verificação de valores ausentes (utilizando resumo_ausentes já calculado ou atualizado)
ausentes = df.isna().sum()
percentuais = (df.isna().mean() * 100).round(2)

resumo_ausentes = pd.DataFrame({
    'Quantidade Ausentes': ausentes,
    'Percentual (%)': percentuais
})

print(" VALORES AUSENTES POR COLUNA ")
display(resumo_ausentes)

# 2. Verificação de linhas duplicadas
total_duplicadas = df.duplicated().sum()
print("\n LINHAS DUPLICADAS ")
print(f"Quantidade de linhas duplicadas (além da primeira ocorrência): {total_duplicadas}")

# 3. Verificação de textos vazios ou preenchidos apenas com espaços
colunas_texto = ["CL_GENERO", "CL_SEG", "PR_CAT", "PR_NOME", "DATA"]

# Dicionário para guardar a quantidade por coluna
espacos_por_coluna = {}
for col in colunas_texto:
    # Verifica quantos registros possuem texto vazio ou apenas espaços em branco
    qtd_em_branco = df[col].astype(str).str.strip().eq("").sum()
    espacos_por_coluna[col] = qtd_em_branco

resumo_espacos = pd.DataFrame(list(espacos_por_coluna.items()), columns=['Coluna', 'Quantidade de Textos Vazios/Espaços'])
print("\n INCONSISTÊNCIAS DE TEXTO (VAZIOS OU ESPAÇOS EM BRANCO)")
display(resumo_espacos)

 VALORES AUSENTES POR COLUNA

           Quantidade Ausentes  Percentual (%)
DATA                         0             0.0
CO_ID                        0             0.0
CL_ID                        0             0.0
CL_GENERO                    0             0.0
CL_EC                        0             0.0
CL_FHL                       0             0.0
CL_SEG                       0             0.0
PR_ID                        0             0.0
PR_CAT                       0             0.0
PR_NOME                      0             0.0

 LINHAS DUPLICADAS
Quantidade de linhas duplicadas (além da primeira ocorrência): 0

 INCONSISTÊNCIAS DE TEXTO (VAZIOS OU ESPAÇOS EM BRANCO)

      Coluna  Quantidade de Textos Vazios/Espaços
0  CL_GENERO                                    0
1     CL_SEG                                    0
2     PR_CAT                                    0
3    PR_NOME                                    0
4       DATA                                    0

### Etapa 4 - Limpeza, Padronização e Tratamento da Base

In [18]:
# 1. Remover colunas desnecessárias e totalmente vazias (Unnamed)
colunas_para_remover = ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
df = df.drop(columns=colunas_para_remover, errors='ignore')
print("Colunas vazias 'Unnamed' removidas com sucesso!")

# 2. Padronização das colunas de texto (Letras maiúsculas e sem espaços extras)
colunas_texto_ajuste = ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']
for col in colunas_texto_ajuste:
    df[col] = df[col].astype(str).str.strip().str.upper()

# Tratar inconsistência de valores '#N/D' identificados na coluna de categoria do produto
df['PR_CAT'] = df['PR_CAT'].replace('#N/D', 'NAO DEFINIDO')
print("Colunas textuais padronizadas e inconsistências como '#N/D' tratadas!")

Colunas vazias 'Unnamed' removidas com sucesso!
Colunas textuais padronizadas e inconsistências como '#N/D' tratadas!

Foi removidas as  colunas  Unnamed , pos  sao  registros  que  podem afetar  a analise futuras

In [19]:
# 3. Eliminação de duplicatas reais (linhas 100% idênticas)
linhas_antes = df.shape[0]
df = df.drop_duplicates()
linhas_depois = df.shape[0]

print(f"Total de linhas antes: {linhas_antes}")
print(f"Total de linhas depois da remoção de duplicatas idênticas: {linhas_depois}")
print(f"Quantidade de linhas duplicadas eliminadas: {linhas_antes - linhas_depois}")

Total de linhas antes: 830000
Total de linhas depois da remoção de duplicatas idênticas: 733447
Quantidade de linhas duplicadas eliminadas: 96553

Foi  tratado as  duplicatas da  base num total de 96553 de  linhas  em  duplicidade ,
o total  de  inicio de resgistro  foi de 83000 e  depois  das  remoçao das  duplicidade ficando em 733447.

In [20]:
# 4. Validação final rápida do novo DataFrame tratado
print("=== Resumo Pós-Tratamento ===")
print(f"Nova quantidade de linhas: {df.shape[0]}")
print(f"Nova quantidade de colunas: {df.shape[1]}")
print("\nDistribuição de categorias corrigida:")
display(df['PR_CAT'].value_counts(dropna=False))

=== Resumo Pós-Tratamento ===
Nova quantidade de linhas: 733447
Nova quantidade de colunas: 10

Distribuição de categorias corrigida:

PR_CAT
ALIMENTOS       384197
HIGIENE         137702
LIMPEZA         128632
BEBIDAS          38264
PET              28553
ACESSORIOS       12871
NAO DEFINIDO      3228
Name: count, dtype: int64

### Etapa 5 - Organização em Funções (Tratamento e Resumo)

In [21]:
def tratar_dados(dataframe):
    """
    Trata, limpa e padroniza o DataFrame de varejo.
    Retorna o DataFrame limpo.
    """
    # Cria uma cópia para evitar warnings de SettingWithCopy
    df_clean = dataframe.copy()

    # 1. Remover colunas desnecessárias e vazias (Unnamed: 10 a 13)
    colunas_para_remover = [
        'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'
        ]
    df_clean = df_clean.drop(columns=colunas_para_remover, errors='ignore')

    # 2. Padronização de textos em colunas específicas
    colunas_texto = [
        'CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME'
        ]
    for col in colunas_texto:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.upper()

    # 3. Tratamento de inconsistência textual específica
    if 'PR_CAT' in df_clean.columns:
        df_clean['PR_CAT'] = df_clean['PR_CAT'].replace('#N/D', 'NAO DEFINIDO')

    # 4. Remoção de duplicatas absolutas (linhas idênticas)
    df_clean = df_clean.drop_duplicates()

    return df_clean

In [33]:
# Para visualizar o DataFrame tratado após a execução da função, usamos a variável global 'df_tratado'
print("Colunas que restaram após o tratamento:")
print(df_tratado.columns.tolist())

print("\nPrimeiras linhas da base tratada:")
display(df_tratado.head())

Colunas que restaram após o tratamento:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

Primeiras linhas da base tratada:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [34]:
def gerar_resumo(dataframe):
    """
    Gera e retorna um resumo estatístico e de distribuição das principais colunas do DataFrame.
    """
    total_linhas = dataframe.shape[0]
    total_colunas = dataframe.shape[1]

    # Distribuição da coluna PR_CAT caso exista no DataFrame
    if 'PR_CAT' in dataframe.columns:
        distribuicao_categorias = dataframe['PR_CAT'].value_counts()
    else:
        distribuicao_categorias = "Coluna PR_CAT não encontrada."

    resumo_dict = {
        "Total de Linhas": total_linhas,
        "Total de Colunas": total_colunas,
        "Distribuicao de Categorias": distribuicao_categorias
    }

    return resumo_dict

In [35]:
# Testando a aplicação prática das duas funções criadas a partir do df_original

# 1. Aplicando a função de tratamento
df_tratado = tratar_dados(df_original)

# 2. Obtendo o resumo estruturado através da função de resumo
resumo_final = gerar_resumo(df_tratado)

# Exibindo os resultados retornados
print(f"Linhas tratadas: {resumo_final['Total de Linhas']}")
print(f"Colunas restantes: {resumo_final['Total de Colunas']}\n")
print("Distribuição de Categorias resultante:")
display(resumo_final['Distribuicao de Categorias'])

Linhas tratadas: 733447
Colunas restantes: 10

Distribuição de Categorias resultante:

PR_CAT
ALIMENTOS       384197
HIGIENE         137702
LIMPEZA         128632
BEBIDAS          38264
PET              28553
ACESSORIOS       12871
NAO DEFINIDO      3228
Name: count, dtype: int64

### Etapa 6 - Análise Estatística de Variável Numérica Relevante

In [26]:
# Selecionando a coluna numérica de relevância: CL_FHL (Tamanho do Núcleo Familiar / Número de Filhos)
estatisticas_fhl = df_tratado['CL_FHL'].describe()

# Exibindo especificamente contagem, média, mínimo e máximo
print("Estatísticas Descritivas da coluna 'CL_FHL' ")
print(f"Contagem de valores válidos: {estatisticas_fhl['count']:.0f}")
print(f"Média:                        {estatisticas_fhl['mean']:.2f}")
print(f"Mínimo:                       {estatisticas_fhl['min']:.0f}")
print(f"Máximo:                       {estatisticas_fhl['max']:.0f}")

Estatísticas Descritivas da coluna 'CL_FHL'
Contagem de valores válidos: 733447
Média:                        1.15
Mínimo:                       0
Máximo:                       4

### Etapa 7 - Segmentação com Filtros e Análise Agrupada (groupby)

In [31]:
# 1. Aplicando o Filtro: Clientes que possuem ao menos 1 dependente/filho (CL_FHL > 0)
df_familias = df_tratado[df_tratado['CL_FHL'] > 0].copy()

# 2. Primeiro agrupamento: Contagem de registros de itens por Categoria de Produto
resumo_categoria = df_familias.groupby('PR_CAT').size().reset_index(name='Qtd_Registros_Itens')

# 3. Segundo agrupamento: Distribuição de registros de itens por Gênero do Cliente cadastrado
resumo_genero = df_familias.groupby('CL_GENERO').size().reset_index(name='Qtd_Registros_Itens')

print(f"Total de registros na base filtrada (Famílias com filhos): {df_familias.shape[0]}\n")

print(" Agrupamento 1: Registros de itens consumidos por Categoria (Famílias com Filhos) ===")
display(resumo_categoria.sort_values(by='Qtd_Registros_Itens', ascending=False))

print("\n Agrupamento 2: Registros de itens por Gênero do Cliente Cadastrado (Famílias com Filhos) ===")
display(resumo_genero)

Total de registros na base filtrada (Famílias com filhos): 348461

 Agrupamento 1: Registros de itens consumidos por Categoria (Famílias com Filhos) ===

         PR_CAT  Qtd_Registros_Itens
1     ALIMENTOS               182527
3       HIGIENE                65400
4       LIMPEZA                61007
2       BEBIDAS                18273
6           PET                13593
0    ACESSORIOS                 6116
5  NAO DEFINIDO                 1545

 Agrupamento 2: Registros de itens por Gênero do Cliente Cadastrado (Famílias com Filhos) ===

  CL_GENERO  Qtd_Registros_Itens
0         F               178400
1         M               170061

### Etapa 8 - Exportação dos Dados Tratados e Relatório Final

In [30]:
# 1. Salvar a base de dados tratada no formato CSV
nome_arquivo_saida = 'varejo_limpo.csv'
df_tratado.to_csv(nome_arquivo_saida, index=False)
print(f"Arquivo '{nome_arquivo_saida}' exportado com sucesso (sem índices)!\n")

# 2. Exibir o número de registros antes e depois do tratamento
registros_brutos = df_original.shape[0]
registros_tratados = df_tratado.shape[0]

print("Comparação de Volumetria ")
print(f"[-] Registros Brutos (Original): {registros_brutos}")
print(f"[+] Registros Higienizados (Limpo): {registros_tratados}")
print(f"[*] Redução líquida de registros redundantes: {registros_brutos - registros_tratados} ({((registros_brutos - registros_tratados)/registros_brutos)*100:.2f}% de dados redundantes removidos)")

Arquivo 'varejo_limpo.csv' exportado com sucesso (sem índices)!

Comparação de Volumetria
[-] Registros Brutos (Original): 830000
[+] Registros Higienizados (Limpo): 733447
[*] Redução líquida de registros redundantes: 96553 (11.63% de dados redundantes removidos)

 Etapa 9 - Conclusões, Recomendações e Limitações da Análise

 Descobertas Numéricas Principais
  Tamanho do Núcleo Familiar (CL_FHL): A média familiar dos clientes ativos na base é de 1.15 dependentes por cadastro. Cerca de 52.49% dos registros totais pertencem a clientes com 0 dependentes (indivíduos de perfil solo), com limite máximo de até 4 dependentes.
 Composição de Consumo por Categoria (Famílias com Filhos): Do total de 348.461 itens comprados por famílias, a categoria ALIMENTOS lidera massivamente com 182.527 registros (52.38%), seguida por HIGIENE com 65.400 registros (18.76%) e LIMPEZA com 61.007 registros (17.50%). As demais categorias somadas representam menos de 12% do volume físico.
Distribuição Volumétrica por Gênero: Na análise do segmento de famílias com filhos, a distribuição física de registros é extremamente equilibrada, sendo 178.400 itens (51.19%) associados ao público feminino e 170.061 itens (48.81%) ao público masculino.

Recomendação de Negócio baseada nos Resultados
Como a categoria ALIMENTOS representa mais da metade dos itens faturados no perfil de famílias com filhos (52.38%), e o núcleo familiar médio possui em torno de 1 a 2 dependentes, a recomendação é implementar campanhas de cross-selling de conveniência familiar. Isso pode ser feito criando ofertas casadas de itens alimentícios de alto giro com produtos de HIGIENE infantil/juvenil (como fraldas e sabonetes, que acumulam 18.76% dos registros de itens), maximizando o tíquete médio das cestas de compras deste segmento.
 Limitação da Análise
A principal limitação técnica identificada é a ausência de dados de faturamento financeiro (preços unitários ou valores totais pagos) nas transações. Esta falta nos impede de analisar o real impacto monetário de cada categoria e segmento de cliente para a receita da empresa, limitando nossa análise exclusivamente à contagem física de volumes de itens comercializados.

In [ ]:
# Gerando o arquivo README.md com as conclusões e detalhes do projeto de forma automatizada
conteudo_readme = """# Mini Projeto - Análise de Dados Varejo
**Estudante:** Roosevelt Freire | **Turma:** T8

##  Resumo do Tratamento da Base de Dados
* **Registros Iniciais:** 830.000 linhas | 14 colunas
* **Registros Finais:** 733.447 linhas | 10 colunas
* **Remoção de Duplicatas:** 96.553 duplicatas sistêmicas idênticas eliminadas.
* **Tratamento de Dados:** Exclusão de 4 colunas nulas corrompidas (`Unnamed`) e substituição de textos inválidos (`#N/D` corrigido para `NAO DEFINIDO` em `PR_CAT`).

##  Conclusões e Descobertas Numéricas
1. **Perfil Familiar (`CL_FHL`):** A média familiar do público é de **1.15 dependentes** por cadastro de cliente. A maior parte da base (cerca de 52%) não possui dependentes cadastrados, e o tamanho familiar máximo registrado na base é de **4** dependentes.
2. **Preferências por Categoria (Famílias com Filhos):** O setor de **ALIMENTOS lidera disparado com 52.38% (182.527 registros)** de participação na cesta física de famílias com filhos, seguido de longe por HIGIENE (18.76%) e LIMPEZA (17.50%).
3. **Distribuição por Gênero:** No segmento de famílias, há um equilíbrio quase perfeito na realização de compras de itens de produtos: **51.19% das linhas associadas a clientes do gênero feminino (178.400 registros)** e **48.81% ao masculino (170.061 registros)**.

##  Recomendação Estratégica
Focar em campanhas de **cross-selling de conveniência familiar**. O varejista deve planejar ofertas combinando produtos alimentícios de alta recorrência com itens de higiene pessoal infantil, aproveitando que estes dois departamentos somados concentram mais de 71% de toda a demanda das famílias monitoradas.

##  Limitação da Análise
A análise está limitada ao fluxo físico (volumetria e quantidade de linhas), uma vez que **não constam dados de preços ou valores de receita** na base disponibilizada, impossibilitando análises financeiras diretas sobre o faturamento do negócio.
"""

with open("README.md", "w", encoding="utf-8") as f:
    f.write(conteudo_readme)

print("Arquivo 'README.md' criado e salvo com sucesso no ambiente!")

### Etapa 10 - Integração e Publicação no GitHub

Para realizar o envio dos arquivos do seu projeto (`Base Varejo.csv`, `varejo_limpo.csv` e `README.md`) para o seu repositório remoto, execute os passos abaixo configurando as suas informações pessoais e credenciais.

In [39]:
# 1. Defina suas credenciais do GitHub (Preencha os campos abaixo)
GITHUB_USER = "Roomoceci"
GITHUB_EMAIL = "juniorfreire623@gmail.com"



# Defina o nome do repositório remoto que você deseja usar
NOME_REPOSITORIO = "miniprojeto_Rooseveltfreire_T8"

import os

# Configurar variáveis globais do Git no ambiente local do Colab
os.system(f'git config --global user.name "{GITHUB_USER}"')
os.system(f'git config --global user.email "{GITHUB_EMAIL}"')

print("Configurações iniciais do Git aplicadas!")

Configurações iniciais do Git aplicadas!

In [42]:
# 2. Inicializar o repositório local e adicionar os arquivos de dados e documentação
!git init

# Garantir que o Git adicione especificamente cada arquivo do miniprojeto
!git add README.md
!git add "Base Varejo.csv"
!git add "varejo_limpo.csv"

# Criar o commit da versão final do miniprojeto
!git commit -m "Commit final: Mini Projeto Varejo - Versão Limpa e Padronizada - Turma T8"

# Configurar o branch principal como 'main'
!git branch -M main

# 3. Vincular e enviar para o repositório remoto no GitHub usando o Token para autenticação
url_remota = f"https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{NOME_REPOSITORIO}.git"

!git remote remove origin 2>/dev/null # Remove vínculo anterior, se existir
!git remote add origin {url_remota}

# Enviar os arquivos finais para a nuvem do seu GitHub
print("Enviando os arquivos para o repositório remoto...")
!git push -u origin main --force

Reinitialized existing Git repository in /content/.git/
fatal: pathspec 'README.md' did not match any files
[main (root-commit) 9fa2084] Commit final: Mini Projeto Varejo - Versão Limpa e Padronizada - Turma T8
 2 files changed, 1563449 insertions(+)
 create mode 100644 Base Varejo.csv
 create mode 100644 varejo_limpo.csv
Enviando os arquivos para o repositório remoto...
remote: Permission to Roomoceci/miniprojeto_Rooseveltfreire_T8.git denied to Roomoceci.
fatal: unable to access 'https://github.com/Roomoceci/miniprojeto_Rooseveltfreire_T8.git/': The requested URL returned error: 403

 Relatório de Problemas Tratados, Decisões e Justificativas

 Problema Encontrado  Decisão Adotada  Justificativa Técnica  Regra de Negócio  Status
 Colunas extras nulas (Unnamed: 10 a 13) Remoção das colunas Eram colunas corrompidas, importadas sem nome e preenchidas com 100\% de valores vazios. Não continham nenhuma informação útil.  Tratado
 Inconsistência textual (#N/D na categoria de produto PR_CAT) | Substituição por NAO DEFINIDO O termo #N/D é um erro de exportação padrão (geralmente do Excel). Substituir por um rótulo textual limpo como NAO DEFINIDO preserva a linha na tabela e permite uma análise sem quebrar filtros de classificação futuros. Tratado
 Espaços nas bordas e letras minúsculas (CL_GENERO, CL_SEG, PR_CAT, PR_NOME)  Remoção de espaços (strip) e conversão para maiúsculo (upper) Inconsistências de digitação (ex: "alimentos" vs "Alimentos " vs "ALIMENTOS") criam categorias fantasmas no agrupamento do pandas. A padronização une registros idênticos sob um único padrão legível. Tratado
 Linhas Duplicadas Absolutas (96.553 ocorrências) Remoção completa via `drop_duplicates() Linhas onde todos os valores (incluindo IDs, datas e produtos) são idênticos são redundâncias operacionais geradas por erros de sistema ou duplicação de lote. Sua permanência distorce médias e volumes reais de venda. Tratado
 Compras repetidas em momentos diferentes (Mesmo cliente / Produto distinto) Mantidos no DataFrame Se um mesmo cliente realiza compras diferentes de produtos diferentes ou em datas diferentes, são transações autênticas de consumo e representam a realidade do negócio. Não foram descartadas.  Mantido (Justificado)

Explicação das Métricas e Medidas

Para interpretar corretamente estes agrupamentos, é fundamental não confundir as diferentes entidades de nossa base de dados:

 O que cada agrupamento acima mede?
  Agrupamento por Categoria: Mede a quantidade absoluta de registros de itens (linhas na tabela) que foram levados nas cestas destas famílias. Por exemplo, se uma linha indica ALIMENTOS, significa que um item pertencente a alimentos foi adicionado em alguma compra.
  Agrupamento por Gênero: Mede o volume de itens associados a cadastros de clientes daquele gênero específico dentro deste grupo filtrado.

Diferenciando as Entidades para Evitar Confusões:
  Registros de Itens (Linhas): Cada linha representa a inclusão de um produto em uma compra.O número total obtido nas tabelas acima (ex: Qtd_Registros_Itens) representa esse volume de itens faturados, e não o número de compras ou clientes individuais.
  Compras (Transações / CO_ID): Uma única compra (CO_ID) pode conter múltiplos itens (várias linhas no nosso dataset). Para contar o número de transações reais, precisaríamos contar os IDs de compra únicos (.nunique()).
  Clientes (CL_ID): Um cliente cadastrado pode realizar várias compras ao longo do tempo. Para sabermos quantos consumidores únicos com filhos temos na base, deveríamos contar os CL_ID exclusivos.
  Faturamento: Como nossa base não contém colunas de preços ou valores monetários monetizados das compras nesta tabela, não podemos estimar o faturamento financeiro diretamente aqui, apenas o volume físico de movimentação de produtos.

### Explicação e Interpretação dos Resultados

 Unidade Analisada: A unidade de análise desta coluna é a quantidade de pessoas por dependentes que compõem o núcleo familiar do cliente cadastrado.

 Explicação de 2 Resultados Obtidos:
   Média 1,15: O valor médio de aproximadamente 1,15 indica que, na média geral da base de clientes ativos, cada cadastro possui entre 1 e 2 dependentes familiares associados. Isso sugere que o público-alvo principal do varejo possui famílias de pequeno a médio porte.
  
   Mínimo 0 e Máximo 4: O valor mínimo mostra a presença de clientes com perfil individual (sem filhos/dependentes registrados na base), enquanto o limite superior máximo é de até 4 dependentes por núcleo familiar nesta amostra, indicando um teto claro nos registros de segmentação da empresa.